#!/bin/bash

#xrdp

sudo apt install xrdp -y
systemctl show -p SubState --value xrdp
sudo adduser xrdp ssl-cert  

#firewall
sudo apt install ufw
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
sudo ufw allow 631
sudo ufw allow 3389
sudo ufw enable

#printer 
sudo apt install cups
sudo usermod -a -G lpadmin pi
sudo sed -i 's/Listen localhost:631/Listen 0.0.0.0:631/g' /etc/cups/cupsd.conf
sudo cupsctl --remote-admin --remote-any --share-printers
echo 'ServerAlias *' | sudo tee -a /etc/cups/cupsd.conf
sudo service cups restart

#apache
sudo apt install apache2 -y
sudo apt install libapache2-mod-wsgi-py3 -y
sudo useradd -m -g www-data -G lpadmin django
sudo mkdir /srv/covid
sudo chown django:www-data /srv/covid
sudo -u django mkdir /srv/covid/pdfs
sudo -u django chmod 775 /srv/covid/pdfs
sudo -u django mkdir /srv/covid/static
sudo -u django mkdir /srv/covid/covidtests

#python3
sudo apt install python3 python3-venv python3-pip -y

sudo a2enmod proxy
sudo a2enmod proxy_http
sudo a2enmod ssl

sudo bash -c "cat > /etc/apache2/sites-enabled/000-default.conf <<'EOF'
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
    Alias /static /srv/covid/static
    <Directory /srv/covid/static>
        Require all granted
    </Directory>
    Alias /static /srv/covid/pdfs
    <Directory /srv/covid/pdfs>
        Require all granted
    </Directory>
    <Directory /srv/covid/covidtests>
        <Files wsgi.py>
            Require all granted
        </Files>
    </Directory>
    WSGIDaemonProcess django python-path=/srv/covid/covidtests python-home=/srv/covid/covidtests/djenv
    WSGIProcessGroup django
    WSGIScriptAlias / /srv/covid/covidtests/covidtests/wsgi.py
</VirtualHost>
<VirtualHost *:443>
    SSLEngine on
    SSLCertificateFile /etc/apache2/server.crt
    SSLCertificateKeyFile /etc/apache2/server.key
    ProxyPass / http://localhost/
    ProxyPassReverse / http://localhost/
</VirtualHost>
EOF"

sudo openssl req -new -x509 -days 365 -subj "/C=AT/ST=Tirol/L=Innsbruck/O=covidschnelltestsoftware/CN=local.covidschnelltestsoftware.de" -nodes -out /etc/apache2/server.crt -keyout /etc/apache2/server.key

cd /srv/covid/covidtests
sudo -u django python3 -m venv djenv


#django and covidsoftware
sudo -i -u django bash << EOF
source djenv/bin/activate
python3 -m pip install django
python3 -m pip install PyPDF2 reportlab CM_Text_sdk_python requests phonenumbers
cd /srv/covid
wget --no-check-certificate --user user --password "covid-19?" https://covidschnelltestsoftware.de/hidden/rpi4.tar.gz
tar xf rpi4.tar.gz
EOF

sudo chown www-data:www-data /srv/covid/covidtests
sudo chown www-data:www-data /srv/covid/covidtests/db.sqlite3


#restart services
sudo systemctl restart apache2
